Ext.define('WX.model.BaseData.AgentDepartmentModel', {
	extend: 'Ext.data.Model',
	idProperty: 'ID',
	fields: [
		{ name: 'ID' },
		{ name: 'Name' },
		{ name: 'Type' },
		{ name: 'UserID' },
		{ name: 'UserName' },
		{ name: 'IsHQ' },
		{ name: 'LegalPerson' },
		{ name: 'IDNumber' },
		{ name: 'Email' },
		{ name: 'WeChatOAPassword' },
		{ name: 'MobilePhoneNo' },
		{ name: 'BusinessLicenseImgUrl' },
		{ name: 'LegalPersonIDCardFrontImgUrl' },
		{ name: 'LegalPersonIDCardBehindImgUrl' },
		{ name: 'CompanyAddress' },
		{ name: 'WeChatAppID' },
		{ name: 'WeChatAppSecret' },
		{ name: 'WeChatMchID' },
		{ name: 'WeChatMchKey' },
		{ name: "MeChatMchPassword" },
		{ name: 'Bank' },
		{ name: 'BankCard' },
		{ name: 'ApproveStatus' },
		{ name: 'Type' },
		{ name: 'CreatedDate' },
	]
});