Ext.define("WX.model.BaseData.CarBitCoinProductModel", {
	extend: "Ext.data.Model",
	idProperty: "ID",
	fields: [
		{ name: "Index" },
		{ name: "Name" },
		{ name: "Code" },
		{ name: "ImgUrl" },
		{ name: "CarBitCoin" },
		{ name: "UpperLimit" },
		{ name: "IsPublish" },
		{ name: "IsCombo" },
		{ name: "IsRecommend" },
		{ name: "Stock" },
		{ name: "CreatedUser" },
		{ name: "EffectiveDate" },
		{ name: "ExpiredDate" },
		{ name: "CreatedDate" },
		{ name: "Horsepower" },
		{ name: "BasePrice" },
		{ name: "PriceSale" },
		{ name: "CarBitCoinProductType" },
		{ name: "CommissionRate" },
		{ name: "IsCanCarBitCoinExchange" },
		{ name: "Unit" },
		{ name: "Introduction" },
		{ name: "DeliveryNotes" },
	]
});