Ext.define('WX.model.BaseData.ConsumeHistoryModel', {
	extend: 'Ext.data.Model',
	fields: [
		{ name: 'Name' },
		{ name: 'MobilePhoneNo' },
		{ name: 'PlateNumber' },
		{ name: 'TradeNo' },
		{ name: 'Consumption' },
		{ name: 'TradeCount' },
		{ name: 'Unit' },
		{ name: 'Price' },
		{ name: 'BasePrice' },
		{ name: 'GrossProfit' },
		{ name: 'Remark' },
		{ name: 'DepartmentName' },
		{ name: 'TradeMoney' },
		{ name: 'Source' },
		{ name: 'CreatedDate' },
	],
});