Ext.define("WX.model.BaseData.MemberModel", {
    extend: "Ext.data.Model",
    idProperty: "ID",
    fields: [
        { name: "ID" },
        { name: "CardID" },
        { name: "Card" },
        { name: "CardNumber" },
        { name: "Status" },
        { name: "CardBalance", type: "number" },
        { name: "Source" },
        { name: "Name" },
        { name: "Sex" },
        { name: "MobilePhoneNo" },
        { name: "Birthday", type: "date" },
        { name: "PlateList" },
        { name: "InsuranceExpirationDate", type: "date" },
        { name: "WeChatOpenID" },
        { name: "Password" },
        { name: "CreatedUserID" },
        { name: "CreatedUser" },
        { name: "CreatedDate", type: "date" },
        { name: "LastUpdateUserID" },
        { name: "LastUpdateUser" },
        { name: "LastUpdateDate", type: "date" },
        { name: "PhoneLocation" },
        { name: "OwnerDepartmentID" },
        { name: "OwnerDepartment" },
        { name: "MemberGroupID" },
        { name: "MemberGradeName" },
        { name: "Point" },
        { name: "CardType" },
        { name: "CardTypeDesc" },
        { name: "WeChatOpenID" },
        { name: "DepartmentName" },
		{ name: "DepartmentAddress" },
		{ name: "IsStockholder" },
		{ name: "DiscountRate" },
		{ name: "ConsumePointRate" },
    ]
});