Ext.define("WX.model.BaseData.ProductModel", {
	extend: "Ext.data.Model",
	idProperty: "ID",
	fields: [
		{ name: "Index" },
		{ name: "Name" },
		{ name: "Code" },
		{ name: "ImgUrl" },
		{ name: "Points" },
		{ name: "UpperLimit" },
		{ name: "IsPublish" },
		{ name: "IsRecommend" },
		{ name: "Stock" },
		{ name: "CreatedUser" },
		{ name: "EffectiveDate" },
		{ name: "ExpiredDate" },
		{ name: "CreatedDate" },
		{ name: "BasePrice" },
		{ name: "PriceSale" },
		{ name: "ProductType" },
		{ name: "CommissionRate" },
		{ name: "IsCanPointExchange" },
		{ name: "Unit" },
		{ name: "Introduction" },
		{ name: "DeliveryNotes" },
	]
});