Ext.define("WX.model.BaseData.ProductModel", {
	extend: "Ext.data.Model",
	idProperty: "ID",
	fields: [
		{ name: "Index" },
		{ name: "Name" },
		{ name: "Code" },
		{ name: "ImgUrl" },
		{ name: "Points" },
		{ name: "UpperLimit" },
		{ name: "IsInternaCollection" },
		{ name: "IsPublish" },
		{ name: "IsCombo" },
		{ name: "IsRecommend" },
		{ name: "Stock" },
		{ name: "CreatedUser" },
		{ name: "EffectiveDate" },
		{ name: "ExpiredDate" },
		{ name: "CreatedDate" },
		{ name: "CostPrice" },
		{ name: "WholesalePrice"},
		{ name: "BasePrice" },
		{ name: "PriceSale" },
		{ name: "ProductType" },
		{ name: "IsCommissionRate" },
		{ name: "CommissionRate" },
		{ name: "CommissionMoney" },
		{ name: "IsSalesmanCommissionRate" },
		{ name: "SalesmanCommissionRate" },
		{ name: "SalesmanCommissionMoney" },
		{ name: "IsWholesaleCommissionRate" },
		{ name: "WholesaleCommissionRate" },
		{ name: "WholesaleCommissionMoney" },
		{ name: "IsWholesaleConstructionCommissionRate" },
		{ name: "WholesaleConstructionCommissionRate" },
		{ name: "WholesaleConstructionCommissionMoney" },
		{ name: "IsCanPointExchange" },
		{ name: "Unit" },
		{ name: "Introduction" },
		{ name: "DeliveryNotes" },
		{ name: "GraphicIntroduction" },
	]
});