///<referencepath="../../ext/ext-all-dev.js"/>
Ext.define('WX.model.BaseData.RechargeHistoryModel', {
    extend: 'Ext.data.Model',
    idProperty: 'ID',
    fields: [
        { name: "ID" },
        { name: "TradeNo" },
        { name: "OutTradeNo" },
        { name: "CardID" },
        { name: "CardNumber" },
        { name: "MemberName" },
        { name: "CardBalance" },
        { name: "TradeAmount" },
        { name: "GiveAmount" },
        { name: "PaymentType" },
        { name: "TradeSource" },
        { name: "TradeDepartment" },
        { name: "CreatedUser" },
        { name: "CreatedDate" },
        { name: "StartDate" },
        { name: "FinishDate" },
        { name: "TradeCount" },
        { name: "RechargeSum" },
        { name: "TotalAmount" },
        { name: "TotalGiveAmount" },
        { name: "HasDraw" },
        { name: "TotalInvoiceAmount" },
        { name: "HasDrawReceipt" },
        { name: "DrawReceiptMoney" },
        { name: "DrawReceiptUserId" },
        { name: "DrawReceiptUser" },
        { name: "DrawReceiptDepartment" },
        { name: "ReportType" },
        { name: "BusinessType" },
        { name: "CardRemark" },
        { name: "CardTypeDesc" },
    ]
});