Ext.define('WX.model.BaseData.RecruitmentModel', {
	extend: 'Ext.data.Model',
	idProperty: 'ID',
	fields: [
		{ name: 'ID' },
		{ name: 'Recruiter' },
		{ name: 'Position' },
		{ name: 'StartDate' },
		{ name: 'LegalPerson' },
		{ name: 'IDNumber' },
		{ name: 'Email' },
		{ name: 'WeChatOAPassword' },
		{ name: 'MobilePhoneNo' },
		{ name: 'BusinessLicenseImgUrl' },
		{ name: 'LegalPersonIDCardFrontImgUrl' },
		{ name: 'LegalPersonIDCardBehindImgUrl' },
		{ name: 'CompanyAddress' },
		{ name: 'WeChatAppID' },
		{ name: 'WeChatAppSercret' },
		{ name: 'WeChatMchKey' },
		{ name: "MeChatMchPassword" },
		{ name: 'Bank' },
		{ name: 'BankCard' },
		{ name: 'CreatedDate' },
	]
});